version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo Build started on 'date'
      # build docker images
      - echo Building production docker image
      - docker build -t luckson/techivity-react-app ./client
      - docker build -t luckson/techivity-api-server ./Server
      - docker build -t luckson/techivity-api-nginx ./nginx
      # log in to the Docker CLI
      - echo "$DOCKER_PW" | docker login -u 

  post_build: 
    commands:
      - echo Pushing the Docker Images
      - docker push luckson/techivity-react-app 
      - docker push luckson/techivity-api-server
      - docker push luckson/techivity-api-nginx

